### ISSUE TITLE
Huggingface model ValueError

### ISSUE THREAD

**Issue by daviddwlee84** [mymusise/gpt2-quickly#1]
I found this problem this morning, and it worked fine yesterday. I think maybe the model checkpoint `mymusise/gpt2-medium-chinese` was accidentally overwritten on the Huggingface.

* [mymusise/gpt2-medium-chinese · Hugging Face](https://huggingface.co/mymusise/gpt2-medium-chinese)
* [gpt2-quickly.ipynb - Colaboratory](https://colab.research.google.com/github/mymusise/gpt2-quickly/blob/main/examples/gpt2_quickly.ipynb)

```txt
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-18d2686f4db3> in <module>()
      3 tokenizer = BertTokenizer.from_pretrained("mymusise/gpt2-medium-chinese")
      4 
----> 5 model = TFGPT2LMHeadModel.from_pretrained("mymusise/gpt2-medium-chinese")

3 frames
<__array_function__ internals> in reshape(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: cannot reshape array of size 6160128 into shape (8021,1024)
```

> BTW, as your model checkpoint is TensorFlow version. I'm wondering if it is able to transform to PyTorch version?

**Comment by mymusise** [comment]
Thanks for your feedback! Fixed now.
BTW, `gpt2-medium-chinese` is still in testing, the available version will take a while.

**Comment by mymusise** [comment]
> BTW, as your model checkpoint is TensorFlow version. I'm wondering if it is able to transform to PyTorch version?

I haven't tried this before, but I find the [`load_tf_weights`](https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.save_pretrained) params may help.

**Comment by mymusise** [comment]
> BTW, as your model checkpoint is TensorFlow version. I'm wondering if it is able to transform to PyTorch version?

And, this may help: https://huggingface.co/transformers/model_sharing.html

> and if you trained your model in TensorFlow and have to create a PyTorch version, adapt the following code to your model class:
> ```
> >>> pt_model = DistilBertForSequenceClassification.from_pretrained("path/to/awesome-name-you-picked", from_tf=True)
> >>> pt_model.save_pretrained("path/to/awesome-name-you-picked")
> ```

**Comment by daviddwlee84** [comment]
Thank you for fixing it and the explanation. Very helpful :D

**Comment by mymusise** [comment]
Closing it, reopen if it need.
