### ISSUE TITLE
关于训练素材和配置请教大佬

### ISSUE THREAD

**Issue by 850886470** [mymusise/gpt2-quickly#3]
大佬能否帮忙解答3个问题：

1.请问这个gpt2-medium的训练语料是什么呀
2.请问是什么显卡才能足够从头训练
3.训练了多久

提前感谢大佬

![u=915485820,3681083199 fm=11 gp=0](https://user-images.githubusercontent.com/19247880/105689400-ad47c780-5f35-11eb-9491-ffcf649de13c.jpeg)

**Comment by mymusise** [comment]
1. 用的是[wiki2019zh_corpus](https://github.com/brightmart/nlp_chinese_corpus)
2. 3.  要训练medium量级的至少要12G显存，速度我认为 RTX20系列以上最好，像TITAN这类的专业卡更好，我用的一块TITAN大概训练了一周多吧

**Comment by 850886470** [comment]
感谢

**Comment by mymusise** [comment]
更新了下显存大小要求，有问题再继续交流，先关掉了
