### ISSUE TITLE
finetune的时候内存占用超过32G

### ISSUE THREAD

**Issue by 850886470** [mymusise/gpt2-quickly#4]
大佬，我按照readme从上到下执行命令（只跳过了train.py ），使用cpu只为看看能不能跑通。但最后进行finetune的时候，直接超过我32G内存了。有办法减少些吗。。

**Comment by mymusise** [comment]
你的语料很大吗，很大的话可以考虑用`TFRecord`， 最近也有计划把数据预处理迁移到`TFRecord`

**Comment by 850886470** [comment]
> 你的语料很大吗，很大的话可以考虑用`TFRecord`， 最近也有计划把数据预处理迁移到`TFRecord`

就是用的git项目里原有的诗歌内容。。没做什么修改。大佬如果直接用诗歌训练正常会占用多少内存呀。上午我把batch_size减少成1了，可以运行一会了，但运行到一半还是会超过32G。

我原以为诗歌语料32G足够了。。 我再把诗歌减少一半试试

**Comment by mymusise** [comment]
好像上次换成sentenceprice后导致了一些bug，我修复下，稍等一会

**Comment by mymusise** [comment]
修复了构建字典的bug，不过好像你这个问题不是这个导致的，应该是上次我改动了测试的参数配置，不过我本地和[colab](https://colab.research.google.com/github/mymusise/gpt2-quickly/blob/main/examples/gpt2_quickly.ipynb)上运行了好像都不会占用32G内存这么多，你有用GPU吗？
或者你试试现在的测试参数[配置](https://github.com/mymusise/gpt2-quickly/blob/main/configs/test.py)

**Comment by 850886470** [comment]
现在参数可以了。我后来也把层数，token减少了。

感谢大佬，感觉开始入门了。
