### ISSUE TITLE
 执行python build_tokenizer.py时出现错误

### ISSUE THREAD

**Issue by TralMac** [mymusise/gpt2-quickly#7]
大佬你好，我在按照requirements.txt配置环境后执行python build_tokenizer.py时出现了下列错误

(gpt2) PS C:\Users\qb\Desktop\gpt2-quickly-main> python build_tokenizer.py
'spm_train' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'mv' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

请问这种情况该如何解决呢？本人小白一枚，还请包涵指教😢

**Comment by mymusise** [comment]
你可能需要本地安装一下 `sentencepiece`

**Comment by mymusise** [comment]
> 'mv' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。

'mv'是linux/unix的命令，建议最好找个linux机器跑，我没在win环境测试过，可能会有不少坑。

**Comment by gongjiaxin** [comment]
[你好](https://img03.in66.cc/2D226176-3867-439A-BAEF-A1C677BFA426.png)
